local.file_match "airflow_logs" {
  path_targets = [
    {
      "__path__" = "/opt/airflow-logs/dag_id=*/run_id=*/task_id=*/*.log",
      "job"      = "airflow_logs",
      "service"  = "airflow",
    },
  ]
}

local.file_match "spark_event_logs" {
  path_targets = [
    {
      "__path__" = "/opt/spark-events/*",
      "job"      = "spark_event_logs",
      "service"  = "spark",
    },
  ]
}

loki.source.file "airflow" {
  targets    = local.file_match.airflow_logs.targets
  forward_to = [loki.write.default.receiver]
}

loki.source.file "spark" {
  targets    = local.file_match.spark_event_logs.targets
  forward_to = [loki.write.default.receiver]
}

loki.write "default" {
  endpoint {
    url = "http://loki:3100/loki/api/v1/push"
  }
}
